# Tässä osastossa sinun pitää määrittää laitteelle oman wifi verkkosi tiedot
# laite yhdistyy wifiin ja yrittää ottaa yhteyttä määrittämääsi MQTT brokeriin, jonne se lähettää logit yms tiedot
wifi:
#päivitä wifi verkkosi tiedot tähän " " merkkien väliin, juuri kuten näet ne esimerkiksi kännykältä
  ssid: "xxxxx"
  password: "xxxxxxxx"
# päätä manuaalinen IP osoite, OTA toimii paremmin: tässä yksi esimerkki, mikä se voisi olla. 
# nämä numerot riippuvat wifi verkostasi.
  manual_ip:
    static_ip: 192.168.1.100
    subnet: 255.255.255.0
    gateway: 192.168.1.0

# Wifin yli tehtävä firmispäivytys
# aseta oma salasanasi, jotteivat hakkerit pääse päivittelemään sinulle mitään ylimääräistä softaa
ota:
  password: "password"
  
# mqtt:tä eli tietokoneelle lämpötilojavarten tarvitset konffata verkossasi olevan mqtt brokerin
# jos et käytä mqtt:tä poista kaikki mitä alla on
# broker: riville tulee IP osoite mqtt brokerillesi, esim 192.168.1.123
mqtt:
  broker: 192.168.1.xxx 
  id: mqtt_client
#kirjoita brokerillasi tunnistettava username alapuoliseen riviin : merkin jälkeen (yksi välilyönti ennen käyttäjänimeä)
  username: "username"
#kirjoita brokerisi käyttäjän salasana alapuoliseen riviin : merkin jälkeen (yksi välilyönti ennen käyttäjänimeä)
  password: "password"
#mqtt viestin alkuosa, muuta tämä haluamaksesi tai pidä tällaisena
  topic_prefix: mzl_ln35/lampotilat

# logit päälle, jotta saadaan PC:lle tieto, mitä laite tekee. Esim. pääseekö wifiin, mitä lämpöjä mittaa yms
logger:

substitutions:
#kaksi seuraavaa riviä pitää säätää jokaisen oman rautansa mukaiseksi
  platform_type:        'esp8266'
  board_type:           'd1_mini_lite'
# dallasien osoitteet:
  dallas_address_kenno: '0x653C01D607697928'
  dallas_address_ulko:  '0x93000802B67D1E10'
  topic_kenno:          'pub/xxx/xxx/xxx/lampotila' #Jos käytät IOTGurua tarvitset tähän katsoa mittaukselle avaimesi
  topic_ulko:           'pub/xxx/xxx/xxx/lampotila' #Jos käytät IOTGurua tarvitset tähän katsoa mittaukselle avaimesi
# IO-pinnit:
  dallas_pinni:         'D7' # 1-wire lämpötila-anturien pinni
  rele_pinni:           'D1' # Releen/transistorin pinni
  