# Update your wifi details to section below
wifi:
  ssid: "xxxxx"
  password: "xxxxxxxx"
# Set manual IP address so that wireless "OTA" update will work more reliably
# Check these number from your wifi network
  manual_ip:
    static_ip: 192.168.1.100
    subnet: 255.255.255.0
    gateway: 192.168.1.0

# enalbes firmware updates over wifi 
# set your unique password to prevent hackers to modify your device
ota:
  password: "password"

# MQTT broker configuration
mqtt:
  broker: 192.168.1.xxx 
  id: mqtt_client
  username: change_this
  client_id: change_this
  password: change_this
#mqtt message prefix, change this to what you want
  topic_prefix: msz_ln/temperature

# In case of you are using IoT Guru (iotguru.io), uncomment and use data below.
# You have to check correct values from your IoT Guru web service
# broker: 195.201.219.208
# username: user short identifier
# client_id: device short identifier
# password: device key

# enable logging to terminal - you can get log messages over wifi
logger:

substitutions:
# define these values according to your hardware see: https://esphome.io/index.html
  platform_type:        'esp8266'
  board_type:           'd1_mini'

# addresses for your dallas DS18B20 temperature sensors - you need to update these
  dallas_address_heat_exchanger_temp: '0x653C01D607697928'
  dallas_address_outdoor_temp:         '0x93000802B67D1E10'

# MQTT topics. These are inside single quotes:
  topic_heatexchanger:      'pub/xxx/xxx/xxx/temperature' #if you will use IOT guru, please uncomment and update this to get graphs working
  topic_outdoor:            'pub/xxx/xxx/xxx/temperature' #if you will use IOT guru, please uncomment and update this to get graphs working
  topic_delta:              'pub/xxx/xxx/xxx/delta'

# MQTT topics. Notice that these are inside both single and double quotes:
  topic_state:                          '"pub/xxx/xxx/xxx/state"'
  topic_excess_timer_state:             '"pub/xxx/xxx/xxx/excess_timer_state"'
  topic_min_heating_timer_state:        '"pub/xxx/xxx/xxx/min_heating_timer_state"'
  topic_defrosting_timer_state:         '"pub/xxx/xxx/xxx/topic_defrosting_timer_state"'
  topic_start_defrosting_timer_state:   '"pub/xxx/xxx/xxx/topic_start_defrosting_timer_state"'
  topic_force_defrost_timer_state:      '"pub/xxx/xxx/xxx/force_defrost_timer_state"'
  topic_reset_timer_state:              '"pub/xxx/xxx/xxx/reset_timer_state"'
  topic_error:                          '"pub/xxx/xxx/xxx/error"'

# IO-pins:
  dallas_pin: 'D2' # pin for DS18B20 1-wire temperature sensors
  relay_pin:  'D0' # pin for controlling relay
