# Update your wifi details to section below
wifi:
  ssid: "xxxxx"
  password: "xxxxxxxx"
# Set manual IP address so that wireless "OTA" update will work more reliably
# Check these number from your wifi network
  manual_ip:
    static_ip: 192.168.1.100
    subnet: 255.255.255.0
    gateway: 192.168.1.0

# enalbes firmware updates over wifi 
# set your unique password to prevent hackers to modify your device
ota:
  password: "password"
  
# MQTT broker configuration
# In case of you are using IoT Guru (iotguru.io), uncomment and use data above. You have to check correct values from your IoT Guru web service
# broker: 195.201.219.208
# username: user short identifier
# client_id: device short identifier
# password: device key

mqtt:
  broker: 192.168.1.xxx 
  id: mqtt_client
  username: change_this
  client_id: change_this
  password: change_this
#mqtt message prefix, change this to what you want
  topic_prefix: mzl_ln35/lampotilat

# enable logging to terminal - you can get log messages over wifi
logger:

substitutions:
# define these values according to your hardware see: https://esphome.io/index.html
  platform_type:        'esp8266'
  board_type:           'd1_mini'

# addresses for your dallas DS18B20 temperature sensors - you need to update these
  dallas_address_heat_exchanger_temp: '0x653C01D607697928'
  dallas_address_outdoor_temp:       '0x93000802B67D1E10'
  
  topic_heatexchanger:      'pub/xxx/xxx/xxx/lampotila' #if you will use IOT guru, please uncomment and update this to get graphs working
  topic_outdoor:           'pub/xxx/xxx/xxx/lampotila' #if you will use IOT guru, please uncomment and update this to get graphs working
# IO-pins:
  dallas_pin:         'D2' # pin for DS18B20 1-wire temperature sensors
  relay_pin:           'D0' # pin for controlling relay
  delay_heating_min: 20min
  