# Copyright (c) 2021 Veli Matti Lastumäki (Velsku at lampopumput.info),
#                    Joonas Ihonen (puu at lampopumput.info),
#                    Ilkka Roivainen (iro at lampopumput.info)
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


# Do not share with anyone or push into the repositoty!

#########################################################################################################
##              This WiFi module is for a standalone Mitsurunner.                                      ##
##              ------------------------------------------------                                       ##
## WiFi is enabled at startup. If WiFi connection is missing for more than 10 minutes                  ##
## continuously, WiFi will be disabled until next boot                                                 ##
## When WiFi is enabled:                                                                               ##
##  * status of the Mitsurunner can be viewed via a web browser at the Mitsurunner's local IP address  ##
##  * OTA-flashing can be done                                                                         ##
#########################################################################################################

# !!If your want too use WiFi add your parameters here !!
substitutions:
  my_wifi_ssid: 'YuorSSID'
  my_wifi_password: 'YourPASSWORD'
  my_ota_password: 'OtaPASSWORD'

##########################################################################################################

wifi:
  ssid: "$my_wifi_ssid"
  password: "$my_wifi_password"

  id: wifi_i
  fast_connect: true
  reboot_timeout: $common_reboot_timeout

################################

# Enables firmware updates over wifi
# Set your unique password to prevent hackers to modify your device
ota:
  platform: esphome
  password: "$my_ota_password"

################################

web_server:
  port: 80

################################

interval:                                        ## Monitor WiFi connection
  - interval: 60s
    then:
      - lambda: !lambda |-
          static int n =  0;
          if (id(wifi_i).is_connected()) n = 0;  // wifi connected
          else if (n < 10) n++;                  // Wifi connection missing less than 10 min
          else if (n == 10) {
              n = 999;                           // Wifi connection missing 10 minutes ==> disable Wifi 
              id(wifi_i).disable();
              }

#################################

sensor:

 # RSSI monitoring, reports the WiFi signal strength in dBm
  - platform: wifi_signal
    name: "WiFi Signal dBm"
    id: wifi_signal_dbm
    accuracy_decimals: 0
    update_interval: 15s
    filters:
    - sliding_window_moving_average:
        window_size: 8     #2 min
        send_every: 8      #2 min

